### ISSUE TITLE
Feature requests: SSL/TLS & Retain flag

### ISSUE THREAD

**Issue by iblis82** [goodfield/zway-mqtt#1]
Hi @goodfield and thanks for this great z-way module.

Would it be possible in the future to implement these features:

**SSL/TLS**
Since the module are allowing us to use authentication when connecting to the broker we should also be able to encrypt our credentials.

**Retain flag**
It would be great to have the option to set the Retain flag to "true" so when other clients connect to the broker they will always get the last device messages sent from zway.

Thanks, and keep up the good work :)

**Comment by tellblom** [comment]
I also like to have the retain flag to true, could this be simply adjusted in the code?

**Update:**
I added a line retain = 1; in index.js  just before line:
var ret = new Buffer(la.length + 1);  (somewhere around row 1027) 

And it seems like it fixed the problem

**Comment by uebelack** [comment]
Will never implement ssl, sorry ;-) the mqtt implementation i'm using has no ssl implemented and it would be to much effort for me to do that ...

The retain flag can be configured now ...
