### ISSUE TITLE
Control device with added suffix "set" or "status" not working 

### ISSUE THREAD

**Issue by iblis82** [goodfield/zway-mqtt#2]
When trying to control a device by adding suffix **set** or **status** to the published topic does nothing in zway.

Device: Popp Wall Plug Dimmer
Room: Kontor
Device Name: Skrivebord
Topic Prefix: zway

Publish: **zway/Kontor/Skrivebord/set on**

**Comment by uebelack** [comment]
Hi

that should work ;-) have added a verbose option, so you can see what's going on in the z-wave server log ...

Hope that helps!

David
