### ISSUE TITLE
Set QOS Level

### ISSUE THREAD

**Issue by Tierran** [goodfield/zway-mqtt#4]
I'm not sure that the QOS level is able to be set currently for sending messages to MQTT.  I've had a camel route getting status changes but it appears that I'm always getting the last and 2nd to last message.  I believe this is because messages are being sent at qualityOfService=0.  My preference would be to send the messages at qualityOfService=2.

I tried adding a qos_level definition in the module.json but that didn't seem to have any effect.  If I can get this to work, I will submit a pull request for my changes but any guidance on what I might be missing would be good as I've tried to hardcode the qos_level and that didn't seem to work either.

**Comment by uebelack** [comment]
With the newest version, qos for publishing and subscription can be defined
