### ISSUE TITLE
topic

### ISSUE THREAD

**Issue by kukachik** [goodfield/zway-mqtt#7]
Hi,
It is not work for me with default mqtt topic. After I changed It on /zway from zway It started work.
PS And thanks for soft.

**Comment by pastukhov** [comment]
You do not need start the topic with /

**Comment by kukachik** [comment]
My topic prefix with /
1480577110: Received PUBLISH from zway (d0, q0, r0, m0, '/zway/Кухня/Освещённость', ... (3 bytes))
topic without /
1480577350: Received PUBLISH from zway (d0, q0, r0, m0, 'zway/Кухня/Освещённость', ... (3 bytes))
If i want subscribe to all topics, i can't. 
/# Didn't work, 
Works only zway/#

**Comment by pastukhov** [comment]
Не очень понял, напишите по русски :)
Посмотрите документацию к mosquitto на предмет топиков https://mosquitto.org/man/mosquitto-8.html

**Comment by kukachik** [comment]
Вчитался в best practices по mqtt и осознал ошибочность моего мнения. 
У меня аппаратное решение, где предполагается стартовый /. И, если корневой топик не начинается с /, оно просто не видит zway. Закрываю, я принал частный случай за проблему.
